import Feed from "../components/Feed";
import Head from "next/head";
import { useEffect } from "react";
import Axios from "axios";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useState } from "react";
export default function Home(props) {
  const [posts, setPosts] = useState([]);
  useEffect(() => {
    async function getData() {
      const { data } = await Axios.get("/api/posts", {
        from: 0,
        amount: 5,
        type: "/",
      });
      setPosts(data);
    }
    getData();
  });
  return (
    <>
      <Head>
        <title>בשבילך - רדילט</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <Feed postsProp={posts} />
    </>
  );
}

// This function gets called at build time on server-side.
// It may be called again, on a serverless function, if
// revalidation is enabled and a new request comes in
export async function getStaticProps(ctx) {
  // query db for posts here.
  // using the next.js api here won't work at build time.
  // so we need to fetch it directly the db.
  // for more info: https://nextjs.org/docs/basic-features/data-fetching/get-static-props#write-server-side-code-directly

  // let postData = {};
  // try {
  //   let url = new URL(
  //     `${process.env.NODE_ENV ? "production" : process.env.URL}/api/posts`
  //   );
  //   let params = {
  //     from: 0,
  //     amount: 5,
  //     type: "/",
  //   };
  //   url.search = new URLSearchParams(params).toString();
  //   let data = await fetch(url);
  //   postData = await data.json();
  // } catch (error) {
  //   postData.posts = [];
  // }
  return {
    props: {
      ...(await serverSideTranslations(ctx.locale, ["menu", "common"])),
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 5 seconds
    revalidate: 5, // In seconds
  };
}
