import Feed from "../components/Feed";
import Head from "next/head";
import Axios from "axios"; // TODO: use Axios to fetch data on the server
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
export default function Home(props) {
  return (
    <>
      <Head>
        <title>בשבילך - רדילט</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <Feed postsProp={props.posts} />
    </>
  );
}

// This function gets called at build time on server-side.
// It may be called again, on a serverless function, if
// revalidation is enabled and a new request comes in
export async function getStaticProps(ctx) {
  // TODO:
  // query db for posts here.
  // using the next.js api here won't work at build time.
  // so we need to fetch it directly the db.
  // for more info: https://nextjs.org/docs/basic-features/data-fetching/get-static-props#write-server-side-code-directly

  let postData = {};
  try {
    // console.log(`env ${process.env.NODE_ENV}`);
    let url = new URL(`${process.env.URL}/api/posts`);

    let params = {
      from: 0,
      amount: 5,
      type: "/",
    };
    url.search = new URLSearchParams(params).toString();
    let data = await fetch(url);
    postData = await data.json();
  } catch (error) {
    console.log(`error ${error}`);

    postData.posts = [];
  }

  return {
    props: {
      ...(await serverSideTranslations(ctx.locale, ["menu", "common"])),
      posts: postData.posts,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 5 seconds
    revalidate: 5, // In seconds
  };
}
