import Head from "next/head";
import Image from "next/image";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import Layout from "../components/Layout";
import Feed from "../components/Feed";
export default function Home() {
  const { t } = useTranslation(["common", "menu"]);
  const THE_TITLE = `${t("for-you", { ns: "menu" })} - ${t("app-name")}`;
  return (
    <>
      <Head>
        <title>{THE_TITLE}</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Layout>
        <Feed />
      </Layout>
    </>
  );
}

// This function gets called at build time on server-side.
// It may be called again, on a serverless function, if
// revalidation is enabled and a new request comes in
export async function getStaticProps(ctx) {
  return {
    props: {
      ...(await serverSideTranslations(ctx.locale, ["menu", "common"])),
    },
  };
}
