import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import Feed from "../components/Feed";
import { useEffect, useState } from "react";
import axios from "axios";
import Post from "../components/Post";

export default function Saved() {
  const { t } = useTranslation(["common", "menu"]);
  const THE_TITLE = `${t("popular", { ns: "menu" })} - ${t("app-name")}`;

  const [posts, setPosts] = useState([]);

  useEffect(() => {
    async function get() {
      const { data } = await axios.get("/api/getSaved");
      setPosts(data.posts);
    }
    get();
  }, []);

  return (
    <>
      <Head>
        <title>{THE_TITLE}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {posts.map(p => (
        <Post post={p} key={p._id} />
      ))}
    </>
  );
}

// This function gets called at build time on server-side.
// It may be called again, on a serverless function, if
// revalidation is enabled and a new request comes in
export async function getStaticProps(ctx) {
  return {
    props: {
      ...(await serverSideTranslations(ctx.locale, [
        "menu",
        "common",
        "admin",
      ])),
    },
  };
}
