import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import { useContext, useEffect, useState } from "react";
import { UserContext } from "../context/UserContext";
import SavedPosts from "../components/SavedPosts";
import SavedIcon from "../components/icons/SavedIcon";

export default function Saved() {
  const { t } = useTranslation(["common", "menu"]);
  const THE_TITLE = `${t("popular", { ns: "menu" })} - ${t("app-name")}`;
  const { user } = useContext(UserContext);

  return (
    <>
      <Head>
        <title>{THE_TITLE}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="feed">
        {user ? (
          <SavedPosts />
        ) : (
          <>
            <div className="m-auto w-1/6 flex fill-error-color mt-36 justify-center animate-bounce">
              <SavedIcon />
            </div>
            <span className="block bg-error-color text-center mt-9 mx-10 text-main-color font-bold text-xl">
              LOG IN TO SEE YOUR SAVED POSTS
            </span>
          </>
        )}
      </div>
    </>
  );
}

// This function gets called at build time on server-side.
// It may be called again, on a serverless function, if
// revalidation is enabled and a new request comes in
export async function getStaticProps(ctx) {
  return {
    props: {
      ...(await serverSideTranslations(ctx.locale, [
        "menu",
        "common",
        "admin",
      ])),
    },
  };
}
